#!/usr/bin/python

#to create results.txt:
#rhino -debug < test.txt | grep -w ENVJSTEST > results.txt
import os, subprocess, sys
verbose=False
if len(sys.argv) > 1 and sys.argv[1]=="-v":
    verbose=True
f = open("test.txt")
p = subprocess.Popen(["rhino", "-debug"], stdin=f, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
p.wait()
oo = p.stdout.readlines()
f.close()

f = open("results.txt")
results = f.readlines()
f.close()

fail=False
for i in oo:
    i = i.rstrip()
    if verbose:
        print i
    if "ENVJSTEST" in i:
        if len(results)==0:
            fail=True
            print "failure: no more results to check against at", i
            break
        r = results.pop(0).rstrip()
        if i != r:
            fail=True
            print "failure: expected", r, "|got|", i
            break
if len(results):
    print "failure: results remaining"
    fail=True
print "FAILURE" if fail else "SUCCESS"

