#!/usr/bin/python
import os, subprocess, sys
verbose=False
if len(sys.argv) > 1 and sys.argv[1]=="-v":
    verbose=True
f = open("test.txt")
p = subprocess.Popen(["rhino", "-debug"], stdin=f, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
p.wait()
f.close
oo = p.stdout.readlines()

f = open("results.txt")
results = f.readlines()
fail=False
for i in oo:
    i = i.rstrip()
    if verbose:
        print "stdout:", i
    if "UNITTEST" in i:
        if len(results)==0:
            fail=True
            print "failure: no more results to check against at", i
            break
        r = results.pop(0).rstrip()
        if i != r:
            fail=True
            print "failure: expected", r, "|got|", i
            break
        else:
            if verbose:
                print "MATCH:", r

if len(results):
    print "failure:", len(results), "results remaining"
    fail=True
print "FAILURE" if fail else "SUCCESS"
